In [1]:
import numpy  as np
# creating arrays
# python array
a = [3,6,9,12,15,18]
print(a)

# numpy array
# 1-D array
b = np.array(a)
print(b)
# 2-D array
b = b.reshape(2,3)
b




[3, 6, 9, 12, 15, 18]
[ 3  6  9 12 15 18]


array([[ 3,  6,  9],
       [12, 15, 18]])

In [2]:
# arrange function
D = np.arange(5,32,2)
print(D)
print(D.shape)
print(D.reshape(2,7))
c = np.arange(1,21).reshape(4,5)
print(c)
b = np.arange(5,25).reshape(5,4)
print(b)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31]
(14,)
[[ 5  7  9 11 13 15 17]
 [19 21 23 25 27 29 31]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [3]:
# zeros(),ones(),eyes()
print(np.zeros(6))
print(np.ones(7))
print(np.eye(7))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [4]:
# multiplication
F = np.dot(c,b)
print(F)
# sum
sum = np.sum(F)
print(sum)
# sum along rows
rows_sum = np.sum(F,axis = 1)
print(rows_sum)
# sum along columns
colum_sum = np.sum(F,axis = 0)
print(colum_sum)

[[ 235  250  265  280]
 [ 560  600  640  680]
 [ 885  950 1015 1080]
 [1210 1300 1390 1480]]
12820
[1030 2480 3930 5380]
[2890 3100 3310 3520]


In [5]:
# LINESPACE 
np.linspace(2,20,5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [6]:
# rand, randn, randit
# 1-D rand
rand_sweetie = np.random.rand(4)
print(rand_sweetie)

# 2-D rand
rand_sweetie = np.random.rand(3,5)
print(rand_sweetie)

# randn 1-D
randn = np.random.randn(3)
print(randn)

randn_2 = np.random.randn(2,3)
print(randn_2)

# randint
randint_1 = np.random.randint(7)
print(randint_1)
randint_2 = np.random.randint(5,10)
print(randint_2)
randint_3 = np.random.randint(3,15,8)
print(randint_3)

# max() & min()
print(randint_3.max())
print(randint_3.min())

arry = np.random.rand(10)
# index of max and min number
print(arry.argmax())
print(arry.argmin())

# mean(), std()
print(np.random.randn(50).mean())
print(np.random.randn(509).std())

[0.90322967 0.51674232 0.12472986 0.92459976]
[[0.06364838 0.99321499 0.39046224 0.8007787  0.76428172]
 [0.01890259 0.80202718 0.26798169 0.54514509 0.28848731]
 [0.409845   0.56424255 0.75498789 0.9401845  0.18523656]]
[-1.44977504 -1.01668165  0.93459661]
[[ 0.47039649  1.99585238  1.23165229]
 [ 1.71368653 -0.18139338  0.18188801]]
1
8
[10  3 10  4  6  9  7  9]
10
3
3
4
0.009330098672417058
0.976890526392451


In [7]:
# Indexing/slicing elements or groups
array = np.arange(6,20)
print(array)
array[10]
print(array[10:13])
print(array[:5])
print(array[6:])

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[16 17 18]
[ 6  7  8  9 10]
[12 13 14 15 16 17 18 19]


In [8]:
# conditions
array_3 = np.arange(2,15)
print(array_3)
array_3 > 6
arry = array_3 > 6
array_3[array_3 > 6]
array_3[(array_3 > 5) & (array_3 < 12)]

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 6,  7,  8,  9, 10, 11])

In [9]:
# Broadcasting
array = np.arange(2,15)
array[1:5] = 7
print(array)


[ 2  7  7  7  7  7  8  9 10 11 12 13 14]


In [10]:
# Arithmetic Operations
array = np.arange(1,10)
print(array)
print(array * array)
print(array - array)
print(array + array)
print(array / array)
print(array + 20)
print(np.sqrt(array))
print(np.exp(array))
print(np.sin(array))
print(np.cos(array))
print(np.log(array))
print(np.sum(array))
print(np.std(array))



[1 2 3 4 5 6 7 8 9]
[ 1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0]
[ 2  4  6  8 10 12 14 16 18]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[21 22 23 24 25 26 27 28 29]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
45
2.581988897471611


In [11]:
# array of n * m matric with the same value
print(np.full((7,7), 7))
C = np.full((3,4), 6, dtype = 'float')
print(C)

print(C.shape)
print(C.size)
print(C.reshape(2,6))


[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
(3, 4)
12
[[6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]]


In [12]:
# flattening an array
E = np.random.randint(7, size = (3,4))
print(E)
print(E.ravel())
print(E.ravel(order = 'F'))
print(E.reshape(2,6))
print(E.reshape(6,2))
print(E.reshape(1,12))

[[1 3 6 2]
 [5 5 1 0]
 [4 6 6 2]]
[1 3 6 2 5 5 1 0 4 6 6 2]
[1 5 4 3 5 6 6 1 6 2 0 2]
[[1 3 6 2 5 5]
 [1 0 4 6 6 2]]
[[1 3]
 [6 2]
 [5 5]
 [1 0]
 [4 6]
 [6 2]]
[[1 3 6 2 5 5 1 0 4 6 6 2]]


In [105]:
# Transpose
E.transpose()

array([[2, 1, 4],
       [2, 4, 6],
       [1, 3, 3],
       [3, 1, 6]])

In [112]:
E = np.random.randint(17, size = (4,6))
print(E)
print(np.vsplit(E, 2))

np.vsplit(E,4)[3] # accessing a particular sub-array after splitting it

[[ 9  9 16  4 10 15]
 [14 11  6  3 11  9]
 [ 3 11  7 14 16  6]
 [ 5 10 15  7  2 13]]
[array([[ 9,  9, 16,  4, 10, 15],
       [14, 11,  6,  3, 11,  9]]), array([[ 3, 11,  7, 14, 16,  6],
       [ 5, 10, 15,  7,  2, 13]])]


array([[ 5, 10, 15,  7,  2, 13]])

In [117]:
# Hsplit Vsplit
print(np.vsplit(E,4)[2])
print(np.hsplit(E,3))


[[ 3 11  7 14 16  6]]
[array([[ 9,  9],
       [14, 11],
       [ 3, 11],
       [ 5, 10]]), array([[16,  4],
       [ 6,  3],
       [ 7, 14],
       [15,  7]]), array([[10, 15],
       [11,  9],
       [16,  6],
       [ 2, 13]])]


In [118]:
# concatenate
f = np.array([5,6,7,8])
g = np.array([1,3,9,7])
np.concatenate((f,g))

array([5, 6, 7, 8, 1, 3, 9, 7])

In [125]:
#Vstack
i = np.array([2,4,6,8])
print(i)
j = np.array([3,6,9,12])
print(j)
k = np.array([10,20,30,40])
print(k)
np.vstack((i,j,k))

[2 4 6 8]
[ 3  6  9 12]
[10 20 30 40]


array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [10, 20, 30, 40]])

In [135]:
# Hstack
i = np.array([2,4,6,8]).reshape(-1,2)
j = np.array([3,6,9,12]).reshape(2, -1)
k = np.array([10,20,30,40]).reshape(-1,2)
np.hstack((i,j,k))

array([[ 2,  4,  3,  6, 10, 20],
       [ 6,  8,  9, 12, 30, 40]])

In [142]:
# linear algebra with numpy arrays
z = np.random.randint(7, size=(4,4))
print(z)

#DETERMINANT OF A MATRIX
det = np.linalg.det(z)
print(det)
#INVERSE OF A MATRIX
inv = np.linalg.inv(z)
print(inv)
#EIG
eig = np.linalg.eig(z)
print(eig)
# DOT
x = np.array([2,4,6,8])
y = np.array([10,10,10,10])
# MATRIX MULTIPLICATION
X = ([[2,2],[3,3]])
Y = ([[4,4],[5,5]])
np.matmul(X,Y)

[[4 4 4 5]
 [3 4 3 1]
 [3 0 2 5]
 [2 3 3 0]]
27.0
[[-0.77777778  1.11111111  0.55555556 -0.44444444]
 [ 0.37037037  0.18518519 -0.40740741 -0.40740741]
 [ 0.14814815 -0.92592593  0.03703704  1.03703704]
 [ 0.40740741 -0.2962963  -0.14814815 -0.14814815]]
(array([11.56932313, -1.89200107, -0.96094302,  1.28362096]), array([[ 0.69689477, -0.49587875, -0.7834715 , -0.18220623],
       [ 0.48125619,  0.37059392,  0.38991078, -0.63156202],
       [ 0.40095451, -0.44716909, -0.02242434,  0.7536103 ],
       [ 0.34923579,  0.64560376,  0.48336233,  0.00134961]]))


array([[18, 18],
       [27, 27]])